<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Engineering.Mcp.Core\UiPath.Engineering.Mcp.Core.csproj" />
    <ProjectReference Include="..\UiPath.Engineering.Mcp.Providers\UiPath.Engineering.Mcp.Providers.csproj" />
    <ProjectReference Include="..\UiPath.Engineering.Mcp.Tools\UiPath.Engineering.Mcp.Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UiPath.Engineering.Mcp.Server.Tests" />
  </ItemGroup>

</Project>
