<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\UiPath.Engineering.Mcp.Core\UiPath.Engineering.Mcp.Core.csproj" />
    <ProjectReference Include="..\UiPath.Engineering.Mcp.Providers\UiPath.Engineering.Mcp.Providers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UiPath.Engineering.Mcp.Tools.Tests" />
    <InternalsVisibleTo Include="UiPath.Engineering.Mcp.Server" />
  </ItemGroup>

</Project>
